sequenceDiagram
  participant browser as Browser
  participant algolia as AlgoliaSearch
  participant photos as photos hollowverse com
  participant cf as CloudFront
  participant s3 as AWS S3 bucket

  browser ->> algolia: Request results for user search
  algolia ->> browser: Return search results (including photo URLs)
  browser ->> photos: Request photo
  photos ->> cf: Request photo
  cf ->> s3: Fetch photo
  s3 ->> cf: Cache photo
  cf ->> photos: Return photo
  photos ->> browser: Return photo
