@startuml
participant Browser as browser
participant "hollowverse.com" as hollowverseCom
participant Splunk as sp
participant "Google Analytics" as ga

activate browser
browser -> hollowverseCom: Request CSS\nand JS files
activate hollowverseCom
hollowverseCom -> browser: Return CSS\nand JS files
deactivate hollowverseCom
browser -> sp: Log events\nto Splunk
browser -> ga: Log events\nto Google Analytics
deactivate browser
@enduml
