@startuml
participant Browser as browser
participant "api.hollowverse.com" as api
participant "photos.hollowverse.com" as photos
participant "AWS Aurora" as aurora
participant "AWS S3 bucket" as s3

activate browser
browser -> api: Request\nNotable Person data
activate api
api -> aurora: Request\nNotable Person data
activate aurora
aurora -> api: Return\nNotable Person data
deactivate aurora
api -> browser: Return\nNotable Person data\n(including photo URL)
deactivate api
browser -> photos: Request photo
activate photos
photos -> s3: Request photo
activate s3
s3 -> photos: Return photo
deactivate s3
photos -> browser: Return photo
deactivate photos
deactivate browser
@enduml
